### ISSUE TITLE
Issue when running pokerweb server in live host

### ISSUE THREAD

**Issue by Mudr0x** [dougdonohoe/ddpoker#4]
Hello,

I made my local that works fine, and deploy it on one of my vps server and it compiles fine etc... But when running the 'pokerweb' command to run the backend web site I had this error:

`[root@vm876 [/home/openholdembot/ddpoker.openholdembot.com]]# pokerweb

     **** Running Poker Wicket Webserver ****

Exec'ing java from pid 3547
2024/Aug/18 16:47:29.977 [*] [main           ::s.poker.wicket.PokerJetty] INFO  >>> STARTING EMBEDDED JETTY SERVER, PRESS ANY KEY TO STOP
2024/Aug/18 16:47:35.411 [*] [main           ::ans.TypeConverterDelegate] WARN  PropertyEditor [com.sun.beans.editors.EnumEditor] found through deprecated global PropertyEditorManager fallback - consider using a more isolated form of registration, e.g. on the BeanWrapper/BeanFactory!
2024/Aug/18 16:47:35.412 [*] [main           ::ans.TypeConverterDelegate] WARN  PropertyEditor [com.sun.beans.editors.EnumEditor] found through deprecated global PropertyEditorManager fallback - consider using a more isolated form of registration, e.g. on the BeanWrapper/BeanFactory!
2024/Aug/18 16:47:35.413 [*] [main           ::ans.TypeConverterDelegate] WARN  PropertyEditor [com.sun.beans.editors.EnumEditor] found through deprecated global PropertyEditorManager fallback - consider using a more isolated form of registration, e.g. on the BeanWrapper/BeanFactory!
2024/Aug/18 16:47:35.436 [main           ::ital.config.LoggingConfig] INFO  Log4j configured using: file:/home/openholdembot/ddpoker.openholdembot.com/code/common/target/classes/config/common/log4j.webapp.properties
2024/Aug/18 16:47:35.437 [main           ::ital.config.LoggingConfig] INFO  Log4j app override file used: file:/home/openholdembot/ddpoker.openholdembot.com/code/pokerwicket/target/test-classes/config/poker/log4j.webapp.properties
2024/Aug/18 16:47:35.512 [main           ::.mail.DDPostalServiceImpl] INFO  Initializing DD Postal Service
2024/Aug/18 16:47:35.513 [main           ::.mail.DDPostalServiceImpl] INFO  DD Postal Service props: {mail.smtp.host=127.0.0.1, mail.smtp.timeout=99000, mail.smtp.connectiontimeout=99000}
2024/Aug/18 16:47:35.523 [ Postal Service::.mail.DDPostalServiceImpl] INFO  Mail Queue started, wait seconds = 10
2024/Aug/18 16:47:35.536 [main           ::web.context.ContextLoader] INFO  Root WebApplicationContext: initialization completed in 4888 ms
2024/Aug/18 16:47:35.705 [main           ::apache.wicket.Application] INFO  [PokerWicketApplication] init: Wicket core library initializer
2024/Aug/18 16:47:35.707 [main           ::apache.wicket.Application] INFO  [PokerWicketApplication] init: Wicket extensions initializer
2024/Aug/18 16:47:35.709 [main           ::tocol.http.WebApplication] INFO  [PokerWicketApplication] Started Wicket version 1.4-rc1 in development mode
********************************************************************
*** WARNING: Wicket is running in DEVELOPMENT mode.              ***
***                               ^^^^^^^^^^^                    ***
*** Do NOT deploy to your live server(s) without changing this.  ***
*** See Application#getConfigurationType() for more information. ***
********************************************************************
2024/Aug/18 16:47:35.738 [main           ::org.mortbay.log          ] WARN  failed SocketConnector@0.0.0.0:8080
java.net.BindException: Address already in use (Bind failed)
        at java.net.PlainSocketImpl.socketBind(Native Method)
        at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:387)
        at java.net.ServerSocket.bind(ServerSocket.java:390)
        at java.net.ServerSocket.<init>(ServerSocket.java:252)
        at java.net.ServerSocket.<init>(ServerSocket.java:196)
        at org.mortbay.jetty.bio.SocketConnector.newServerSocket(SocketConnector.java:78)
        at org.mortbay.jetty.bio.SocketConnector.open(SocketConnector.java:72)
        at org.mortbay.jetty.AbstractConnector.doStart(AbstractConnector.java:252)
        at org.mortbay.jetty.bio.SocketConnector.doStart(SocketConnector.java:145)
        at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:40)
        at org.mortbay.jetty.Server.doStart(Server.java:231)
        at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:40)
        at com.donohoedigital.games.poker.wicket.PokerJetty.main(PokerJetty.java:55)
2024/Aug/18 16:47:35.738 [main           ::org.mortbay.log          ] WARN  failed Server@40f33492
java.net.BindException: Address already in use (Bind failed)
        at java.net.PlainSocketImpl.socketBind(Native Method)
        at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:387)
        at java.net.ServerSocket.bind(ServerSocket.java:390)
        at java.net.ServerSocket.<init>(ServerSocket.java:252)
        at java.net.ServerSocket.<init>(ServerSocket.java:196)
        at org.mortbay.jetty.bio.SocketConnector.newServerSocket(SocketConnector.java:78)
        at org.mortbay.jetty.bio.SocketConnector.open(SocketConnector.java:72)
        at org.mortbay.jetty.AbstractConnector.doStart(AbstractConnector.java:252)
        at org.mortbay.jetty.bio.SocketConnector.doStart(SocketConnector.java:145)
        at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:40)
        at org.mortbay.jetty.Server.doStart(Server.java:231)
        at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:40)
        at com.donohoedigital.games.poker.wicket.PokerJetty.main(PokerJetty.java:55)
2024/Aug/18 16:47:35.739 [main           ::s.poker.wicket.PokerJetty] ERROR java.net.BindException: Address already in use (Bind failed)
        at java.net.PlainSocketImpl.socketBind(Native Method)
        at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:387)
        at java.net.ServerSocket.bind(ServerSocket.java:390)
        at java.net.ServerSocket.<init>(ServerSocket.java:252)
        at java.net.ServerSocket.<init>(ServerSocket.java:196)
        at org.mortbay.jetty.bio.SocketConnector.newServerSocket(SocketConnector.java:78)
        at org.mortbay.jetty.bio.SocketConnector.open(SocketConnector.java:72)
        at org.mortbay.jetty.AbstractConnector.doStart(AbstractConnector.java:252)
        at org.mortbay.jetty.bio.SocketConnector.doStart(SocketConnector.java:145)
        at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:40)
        at org.mortbay.jetty.Server.doStart(Server.java:231)
        at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:40)
        at com.donohoedigital.games.poker.wicket.PokerJetty.main(PokerJetty.java:55)
`

I use ssl https redirection on it, and I can't deactivate it, I don't know if it due to that because locally from my test it works on non secure 'http' connection...  :/

**Comment by Mudr0x** [comment]
Even with Docker I can build it successfully but if I try to run it via Docker I have similar error:

`[root@vm876 [/home/openholdembot/ddpoker.openholdembot.com]]# docker run -it -p 8080:8080 pokerweb
docker: Error response from daemon: driver failed programming external connectivity on endpoint charming_napier (c44afca3831d251d1906abbc258b1eab105c7ee5d270a0ea234442d0f06f8909): Error starting userland proxy: listen tcp4 0.0.0.0:8080: bind: address already in use.`

**Comment by dougdonohoe** [comment]
`PokerJetty` is only meant for development purposes, so don't go down that path.  It's meant only for running in a local development environment.

The `docker` example, is just that, an example of how to deploy and run using Tomcat.  The main purpose of this is to show how to copy the `.war` file to the proper place for Tomcat to recognize it. Note that it is Mac specific due to the use of `DBHOST=host.docker.internal`.   In a real deployment, this would be wherever MySQL is running, either on the same host or some cloud environment.

**Comment by Mudr0x** [comment]
Ok thanks to enlight me.
I see that when launching the docker file build some command are not executed, maybe due to incompatibilties with my server host setup using centos 9 running on AlmaLinux v8.
So I did them manually to test and copied also the .war file manually, changing the DB_HOST to localhost as it is always the address I point for all other webapps I use on.
After I delete the original ROOT folder of default Tomcat webapp and I launch the 'catalina.sh run' script it always fails with the same ip binding error and I see that each time the default ROOT webapp is always reconstitued and seems to never use the ROOT.war that I copied instead.

Maybe you could help me to solve this because I don't have any clue of why? Thanks.

**Comment by dougdonohoe** [comment]
I'm sorry but I am not able to help debug your environment - it could be many reasons.   I can give you a couple of pointers, but the best bet is to ask Google and/or ChatGPT for help.

However, a "address already in use" means what it says - something else is already using port 8080. You can change the port tomcat uses in `/opt/tomcat/conf/server.xml`.

I'm going to close this as this is an issue with your environment.  Good luck!

**Comment by Mudr0x** [comment]
Ok thanks I got it now, I was effectively running other web servers on the same host and when chaging the host port with another port than 8080 it works fine now.  👍
